<template>
  <div class="page-shell animate-fade-in">
    <header class="flex flex-wrap items-end justify-between gap-3">
      <div><p class="eyebrow">Coordinación EPG</p><h2 class="page-title">Docentes y capacidad académica</h2><p class="page-subtitle">Padrón actualizado, grados verificados, afinidad y actividad docente.</p></div>
      <button class="btn-primary" @click="modalTramite=true"><i class="pi pi-plus"></i>Registrar trámite</button>
    </header>

    <div v-if="mensaje" :class="['rounded-md border px-3 py-2 text-xs',error?'border-red-400 bg-red-50 text-red-800 dark:bg-red-950/30 dark:text-red-200':'border-emerald-400 bg-emerald-50 text-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-200']">{{ mensaje }}</div>

    <section class="grid grid-cols-2 gap-3 lg:grid-cols-7">
      <button v-for="m in metricas" :key="m.label" class="card text-left hover:border-cyan-400" @click="m.accion?.()"><p class="text-[10px] uppercase text-slate-500">{{m.label}}</p><p class="mt-1 text-2xl font-bold text-slate-950 dark:text-white">{{m.valor}}</p></button>
    </section>

    <nav class="flex gap-2 border-b border-slate-200 pb-3 dark:border-slate-800">
      <button :class="vista==='padron'?'btn-primary':'btn-outline'" class="btn-sm" @click="vista='padron'"><i class="pi pi-users"></i>Padrón docente</button>
      <button :class="vista==='tramites'?'btn-primary':'btn-outline'" class="btn-sm" @click="vista='tramites';cargarTramites()"><i class="pi pi-inbox"></i>Trámites <span class="badge ml-1">{{resumen.tramites_pendientes||0}}</span></button>
    </nav>

    <template v-if="vista==='padron'">
      <div class="filter-bar grid gap-2 md:grid-cols-[minmax(220px,1fr)_160px_190px_160px_auto]">
        <input v-model="filtros.busqueda" class="input-field" placeholder="Nombre, DNI, correo o especialidad" @keyup.enter="buscar" />
        <select v-model="filtros.nivel" class="input-field" @change="buscar"><option value="">Todos los niveles</option><option>Maestria</option><option>Doctorado</option></select>
        <input v-model="filtros.programa" class="input-field" placeholder="Programa o campo" @keyup.enter="buscar" />
        <select v-model="filtros.verificacion" class="input-field" @change="buscar"><option value="">Toda verificación</option><option value="Padron_EPG">Padrón EPG</option><option value="Pendiente">Pendiente</option></select>
        <button class="btn-primary btn-sm" @click="buscar"><i class="pi pi-search"></i>Buscar</button>
      </div>
      <section class="card overflow-hidden p-0">
        <div class="overflow-auto"><table class="data-table"><thead><tr><th>Docente</th><th>Grados y verificación</th><th>Afinidad</th><th>Actividad</th><th>Estado</th><th></th></tr></thead><tbody>
          <tr v-for="d in docentes" :key="d.id_docente">
            <td><p class="font-semibold text-slate-950 dark:text-white">{{d.nombre_completo}}</p><p class="text-[10px] text-slate-500">{{d.dni||'DNI pendiente'}} · {{d.correo||'sin correo'}}</p></td>
            <td><p class="text-xs">{{d.grados_total}} registro(s)</p><span :class="d.cumple_antiguedad?'badge-graduado':'badge-observado'">{{d.cumple_antiguedad?'Antigüedad verificada':'Revisar antigüedad'}}</span></td>
            <td class="text-xs">{{d.programas_total}} campo(s)</td><td class="text-xs">{{d.actividad_total}} dictado(s)</td>
            <td><span :class="d.estado==='Activo'?'badge-graduado':'badge-caduco'">{{d.estado}}</span><small class="mt-1 block text-slate-500">{{d.estado_verificacion}}</small></td>
            <td><button class="icon-btn" title="Abrir ficha" @click="abrir(d)"><i class="pi pi-arrow-right"></i></button></td>
          </tr><tr v-if="!docentes.length"><td colspan="6" class="py-12 text-center text-slate-500">No hay docentes para estos filtros.</td></tr>
        </tbody></table></div>
        <footer class="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-xs text-slate-500 dark:border-slate-700"><span>{{total}} docentes · página {{pagina}} de {{paginas}}</span><div class="flex gap-2"><button class="btn-outline btn-sm" :disabled="pagina<=1" @click="pagina--;cargar()">Anterior</button><button class="btn-outline btn-sm" :disabled="pagina>=paginas" @click="pagina++;cargar()">Siguiente</button></div></footer>
      </section>
    </template>

    <section v-else class="card overflow-hidden p-0">
      <div class="flex flex-wrap gap-2 border-b border-slate-200 p-3 dark:border-slate-700"><button v-for="e in estadosTramite" :key="e" class="btn-outline btn-sm" @click="filtroTramite=e;cargarTramites()">{{e||'Todos'}}</button></div>
      <table class="data-table"><thead><tr><th>Recepción</th><th>Docente</th><th>Trámite</th><th>Canal</th><th>Estado</th><th></th></tr></thead><tbody><tr v-for="t in tramites" :key="t.uuid"><td class="text-xs">{{fecha(t.fecha_recepcion)}}</td><td>{{t.docente||'Por identificar'}}</td><td><strong>{{t.tipo}}</strong><small class="block text-slate-500">{{t.referencia||t.descripcion||''}}</small></td><td>{{t.canal}}</td><td><span class="badge-proceso">{{t.estado}}</span></td><td><select :value="t.estado" class="input-field text-xs" @change="cambiarEstado(t,$event.target.value)"><option v-for="e in estadosTramite.slice(1)" :key="e">{{e}}</option></select></td></tr></tbody></table>
    </section>

    <div v-if="detalle" class="fixed inset-0 z-50 flex justify-end bg-black/55" @click.self="detalle=null"><aside class="h-full w-full max-w-2xl overflow-y-auto bg-white p-6 shadow-2xl dark:bg-slate-950"><header class="flex justify-between gap-4"><div><p class="eyebrow">Ficha docente</p><h3 class="section-title">{{detalle.nombre_completo}}</h3><p class="mt-1 text-xs text-slate-500">{{detalle.dni||'Sin DNI'}} · {{detalle.correo||'Sin correo'}}</p></div><button class="icon-btn" @click="detalle=null"><i class="pi pi-times"></i></button></header>
      <div class="mt-5 grid gap-3 md:grid-cols-3"><label class="card"><span class="input-label">Estado</span><select v-model="edicion.estado_docente" class="input-field mt-2"><option>Activo</option><option>Inactivo</option><option>De Licencia</option></select></label><label class="card"><span class="input-label">Verificación</span><select v-model="edicion.estado" class="input-field mt-2"><option>Pendiente</option><option>Padron_EPG</option><option>Verificado</option><option>Observado</option></select></label><div class="card"><p class="input-label">Regla interna</p><strong :class="detalle.cumple_antiguedad?'text-emerald-600':'text-amber-600'">{{detalle.cumple_antiguedad?'Cumple':'Pendiente'}}</strong><small class="mt-2 block text-slate-500">{{detalle.antiguedad_requerida_anios}} años desde un grado verificable.</small></div></div>
      <div class="mt-3 flex gap-2"><input v-model="edicion.especialidad" class="input-field flex-1" placeholder="Especialidad principal"/><button class="btn-primary" @click="guardarVerificacion"><i class="pi pi-check"></i>Guardar revisión</button></div>
      <section class="mt-5"><h4 class="font-semibold">Grados y títulos</h4><div class="mt-2 space-y-2"><article v-for="g in detalle.grados" :key="g.id_grado" class="rounded border border-slate-200 p-3 text-xs dark:border-slate-700"><div class="flex justify-between"><strong>{{g.tipo}}</strong><span :class="g.verificado?'badge-graduado':'badge-observado'">{{g.verificado?'SUNEDU':'Por verificar'}}</span></div><p class="mt-1">{{g.denominacion}}</p><p class="text-slate-500">{{g.universidad||'Universidad pendiente'}} · {{g.fecha_diploma||'fecha pendiente'}}</p></article></div></section>
      <section class="mt-5"><div class="flex items-center justify-between"><h4 class="font-semibold">Afinidad por nivel y campo</h4><button class="btn-outline btn-sm" @click="mostrarPrograma=!mostrarPrograma"><i class="pi pi-plus"></i>Añadir</button></div><div class="mt-2 flex flex-wrap gap-2"><span v-for="p in detalle.programas" :key="p.id_programa_docente" class="rounded border border-cyan-300 px-3 py-2 text-xs dark:border-cyan-700"><strong>{{p.nivel}}</strong> · {{p.programa}}</span><span v-if="!detalle.programas.length" class="text-xs text-slate-500">Sin afinidades registradas.</span></div><form v-if="mostrarPrograma" class="mt-3 grid gap-2 md:grid-cols-[130px_1fr_auto]" @submit.prevent="agregarPrograma"><select v-model="programa.nivel" class="input-field"><option>Maestria</option><option>Doctorado</option></select><input v-model="programa.programa" required class="input-field" placeholder="Programa o campo de afinidad"/><button class="btn-primary">Guardar</button></form></section>
      <section class="mt-5"><div class="flex flex-wrap items-center justify-between gap-2"><div><h4 class="font-semibold">Documentos de respaldo</h4><p class="text-xs text-slate-500">CV, consulta SUNEDU, constancias y evidencia administrativa.</p></div><div class="flex gap-2"><select v-model="tipoDocumento" class="input-field w-32 text-xs"><option>CV</option><option>SUNEDU</option><option>Constancia</option><option>Otro</option></select><label class="btn-outline btn-sm cursor-pointer"><i class="pi pi-upload"></i>Cargar<input type="file" class="hidden" @change="cargarDocumento"/></label></div></div><div class="mt-2 space-y-2"><article v-for="d in detalle.documentos" :key="d.uuid" class="flex flex-wrap items-center gap-2 rounded border border-slate-200 p-3 text-xs dark:border-slate-700"><button class="min-w-0 flex-1 text-left" @click="abrirDocumento(d)"><strong class="block truncate">{{d.nombre_archivo}}</strong><span class="text-slate-500">{{d.tipo}} · {{fecha(d.fecha_carga)}} <template v-if="d.tiene_texto">· texto reconocido</template></span></button><select :value="d.estado_revision" class="input-field w-32 text-xs" @change="revisarDocumento(d,$event.target.value)"><option>Pendiente</option><option>Validado</option><option>Observado</option></select></article><p v-if="!detalle.documentos?.length" class="rounded bg-slate-100 p-4 text-xs text-slate-500 dark:bg-slate-900">Aún no hay documentos cargados.</p></div></section>
      <section class="mt-5"><h4 class="font-semibold">Actividad registrada</h4><div class="mt-2 grid grid-cols-2 gap-2"><div v-for="a in detalle.actividades" :key="a.periodo+a.programa" class="rounded bg-slate-100 p-3 text-xs dark:bg-slate-800"><strong>{{a.periodo}}</strong><span class="block text-slate-500">{{a.registros}} registro(s)</span></div></div></section>
    </aside></div>

    <div v-if="modalTramite" class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" @click.self="modalTramite=false"><form class="card w-full max-w-lg" @submit.prevent="crearTramite"><header class="flex justify-between"><h3 class="section-title">Registrar trámite docente</h3><button type="button" class="icon-btn" @click="modalTramite=false"><i class="pi pi-times"></i></button></header><div class="mt-4 space-y-3"><select v-model="nuevo.id_docente" class="input-field"><option value="">Docente por identificar</option><option v-for="d in docentes" :key="d.id_docente" :value="d.id_docente">{{d.nombre_completo}}</option></select><div class="grid grid-cols-2 gap-3"><select v-model="nuevo.canal" class="input-field"><option>MPV</option><option>Fisico</option><option>Interno</option></select><input v-model="nuevo.referencia" class="input-field" placeholder="N.º ticket o referencia" /></div><input v-model="nuevo.tipo" required class="input-field" placeholder="Tipo de trámite" /><textarea v-model="nuevo.descripcion" class="input-field min-h-28" placeholder="Detalle y documentos recibidos"></textarea></div><div class="mt-5 flex justify-end gap-2"><button type="button" class="btn-outline" @click="modalTramite=false">Cancelar</button><button class="btn-primary">Registrar</button></div></form></div>
  </div>
</template>

<script setup>
import {computed,onMounted,reactive,ref} from 'vue'; import api from '../api.js'
const vista=ref('padron'),resumen=ref({}),docentes=ref([]),tramites=ref([]),detalle=ref(null),mensaje=ref(''),error=ref(false),pagina=ref(1),paginas=ref(1),total=ref(0),modalTramite=ref(false),filtroTramite=ref(''),mostrarPrograma=ref(false),tipoDocumento=ref('CV')
const filtros=reactive({busqueda:'',nivel:'',programa:'',verificacion:'Padron_EPG'});const nuevo=reactive({id_docente:'',canal:'MPV',tipo:'',referencia:'',descripcion:''});const edicion=reactive({estado:'Pendiente',estado_docente:'Activo',especialidad:''});const programa=reactive({nivel:'Maestria',programa:''});const estadosTramite=['','Recibido','En_revision','Observado','Atendido','Archivado']
const metricas=computed(()=>[{label:'Padrón actual',valor:resumen.value.padron_epg||0,accion:()=>{filtros.verificacion='Padron_EPG';buscar()}},{label:'Con SUNEDU',valor:resumen.value.con_sunedu||0},{label:'Afinidad Maestría',valor:resumen.value.maestria||0,accion:()=>{filtros.nivel='Maestria';buscar()}},{label:'Afinidad Doctorado',valor:resumen.value.doctorado||0,accion:()=>{filtros.nivel='Doctorado';buscar()}},{label:'Archivo histórico',valor:resumen.value.total||0,accion:()=>{filtros.verificacion='';buscar()}},{label:'Activos por revisar',valor:resumen.value.activos||0},{label:'Trámites pendientes',valor:resumen.value.tramites_pendientes||0,accion:()=>{vista.value='tramites';cargarTramites()}}])
function mostrar(e){const d=e.response?.data?.detail;error.value=true;mensaje.value=typeof d==='string'?d:d?.mensaje||'No se pudo completar la acción.'}
async function cargar(){try{const [r,s]=await Promise.all([api.get('/docentes',{params:{...filtros,page:pagina.value,per_page:40}}),api.get('/docentes/resumen')]);docentes.value=r.data.data;total.value=r.data.total;paginas.value=r.data.total_pages||1;resumen.value=s.data}catch(e){mostrar(e)}}
function buscar(){pagina.value=1;cargar()} async function abrir(d){try{detalle.value=(await api.get(`/docentes/${d.id_docente}`)).data;Object.assign(edicion,{estado:detalle.value.estado_verificacion,estado_docente:detalle.value.estado,especialidad:detalle.value.especialidad||''})}catch(e){mostrar(e)}}
async function guardarVerificacion(){try{detalle.value=(await api.put(`/docentes/${detalle.value.id_docente}/verificacion`,edicion)).data.docente;mensaje.value='Ficha docente actualizada.';error.value=false;await cargar()}catch(e){mostrar(e)}}
async function agregarPrograma(){try{await api.post(`/docentes/${detalle.value.id_docente}/programas`,programa);programa.programa='';mostrarPrograma.value=false;await abrir(detalle.value);await cargar()}catch(e){mostrar(e)}}
async function cargarDocumento(evento){const archivo=evento.target.files?.[0];if(!archivo)return;const form=new FormData();form.append('tipo',tipoDocumento.value);form.append('archivo',archivo);try{await api.post(`/docentes/${detalle.value.id_docente}/documentos`,form);mensaje.value='Documento incorporado a la ficha.';error.value=false;await abrir(detalle.value)}catch(e){mostrar(e)}finally{evento.target.value=''}}
async function abrirDocumento(d){try{const r=await api.get(`/docente-documentos/${d.uuid}/archivo`,{responseType:'blob'});const url=URL.createObjectURL(r.data);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){mostrar(e)}}
async function revisarDocumento(d,estado){try{await api.put(`/docente-documentos/${d.uuid}/revision`,{estado});await abrir(detalle.value)}catch(e){mostrar(e)}}
async function cargarTramites(){try{tramites.value=(await api.get('/docente-tramites',{params:{estado:filtroTramite.value||undefined}})).data.data}catch(e){mostrar(e)}}
async function crearTramite(){try{await api.post('/docente-tramites',{...nuevo,id_docente:nuevo.id_docente?Number(nuevo.id_docente):null});modalTramite.value=false;mensaje.value='Trámite docente registrado.';error.value=false;Object.assign(nuevo,{id_docente:'',canal:'MPV',tipo:'',referencia:'',descripcion:''});await cargar();await cargarTramites()}catch(e){mostrar(e)}}
async function cambiarEstado(t,estado){try{await api.put(`/docente-tramites/${t.uuid}/estado`,{estado,descripcion:t.descripcion||null});await cargarTramites();await cargar()}catch(e){mostrar(e)}} function fecha(v){return v?new Date(v).toLocaleDateString('es-PE'):'-'} onMounted(cargar)
</script>
